# Site settings
title: Head of Data Engineering & AI 
email: mahadevan.varadhan@gmail.com
name: Mahadevan Varadhan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: My Blog
   url: https://cloudmerge.org/
 - title: Git Lab
   url: https://gitlab.com/rvmahadevan
 - title: LinkedIn
   url: https://www.linkedin.com/in/mahadevan-varadhan/
 - title: Google Blog 1
   url: http://mahadevanrv.blogspot.com/
 - title: Google Blog 2
   url: https://mahacloudmerge.blogspot.com/

#Any buzzword skills you want to include
skills:
 - Scala
 - Akka-http
 - Microservices
 - Slick
 - Product management
 - API design
 - Groovy
 - Spring MVC/Boot/Social
 - Gradle
 - Java
 - JPA
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: CTO
   start: 2017
   end: Ongoing
   employer: Basement Crowd
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Engineer
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
gitlab:
 - https://gitlab.com/rvmahadevan/mahadevan.varadhan.io
 - https://gitlab.com/rvmahadevan/googlenlp
 - https://gitlab.com/rvmahadevan/elk-mysql-sql
 - https://gitlab.com/rvmahadevan/credit-lead-prediction
 - https://gitlab.com/rvmahadevan/jupyter_notebook_datascience
 - https://gitlab.com/rvmahadevan/quickrecommendation

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/258813/rhinds
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: 
  I am a data engineer with 16 years experience working in technology. My key technical skill sets are SQL Server BI Tools, Power BI, Redshift, Python, Tableau and Data Studio. <br/>
  I primarily work on developing Data Warehousing, Data Modelling, Data Architecting and contributes toward creating data pipeling and BI reports for business.<br/>
  I am also involved in developing machine learning models including recommendation engine and prediction. <br/>
  I also manage DW/BI team and all data products development involving NLP, AI and machine learning.<br/>
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>SQL</strong>: Working with SQL queries throughout my career. Good experience in writing complex queries, stored procedures, function and views.<br/>
   <strong>Python</strong>: Using Python I developed many data pipelines with Airflow, Dataflow, AWS Glue. Good in Panda and Pyspark. Worked in contributing to Flask and Djangio API's developments.<br/>
   <strong>NLP</strong>Stromng knowledge in NLP and NLP api's. Has used Google NLP services and opensources like NLTK, Hugging Face transformesrs and as well as OpenAI for NLP developments. Has built successful News API product with NLP features.<br/>
   <strong>Cloud platforms</strong>: Has experience working with different cloud environments and their database services. have knowledge in AWS, Google Cloud  and Azure cloud services.<br/>
   <strong>API Development</strong>: Has contributed in API developments using Flask and Django framework. Has knowledge in GraphQL.
   <strong>Machine Learning</strong>: Built recomendation models on content recommendation based on learner preference. Has worked on churn prediction with user experience and feedback.
   <strong>Power BI and Tableau</strong>: Worked on delivering many decision making reports and dashboards using Power BI and Tableau visualization tools.
   In addition to the above key skills, I also worked on many R&D projects using different cloud services and open sources.  